accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # Auth
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('register/', views.registeruser, name='register'),
]

diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    # Diet
    path('add/measured/', views.addmeasured, name='addmeasured'),
    path('add/diet', views.adddiet, name='adddiet'),
]

losingweight/urls.py
from django.contrib import admin
from django.urls import path, include
import diet.views, accounts.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', diet.views.home, name='home'),
    # Auth
    path('accounts/', include('accounts.urls')),
    # Diet
    path('diet/', include('diet.urls')),
    # Measured
    path('measured/', include('measured.urls')),
    # User
    path('user/', diet.views.userpage, name='userpage'),
]

losingweight/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Losing Weight</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'style.css' %}">
  {% block style %}{% endblock %}
</head>

<body data-gr-c-s-loaded="true">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">Cover</h3>
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
          <a class="nav-link" href="#">Features</a>
          <a class="nav-link" href="#">Contact</a>
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'userpage'%}">{{user}}</a>
          <a class="nav-link" href="javascript:{$('#logout').submit()}">Logout</a>
          <form style="display: none;" method="POST" action="{% url 'accounts:logout' %}" id="logout">{% csrf_token %}</form>
          {% else %}
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          {% endif %}
        </nav>
      </div>
    </header>

    {% if error %}
    <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    {% block content %}{% endblock %}

    <footer class="mastfoot mt-auto text-center">
      <div class="inner">
        <p>&copy; Yusuke Ueda {% now 'Y' %}</p>
      </div>
    </footer>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>