accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # Auth
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('register/', views.registeruser, name='register'),
]

diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    # Diet
    path('add/measured/', views.addmeasured, name='addmeasured'),
    path('add/diet', views.adddiet, name='adddiet'),
]

losingweight/urls.py
from django.contrib import admin
from django.urls import path, include
import diet.views, accounts.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', diet.views.home, name='home'),
    # Auth
    path('accounts/', include('accounts.urls')),
    # Diet
    path('diet/', include('diet.urls')),
    # Measured
    path('measured/', include('measured.urls')),
    # User
    path('user/', diet.views.userpage, name='userpage'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    SEX_CHOICES = [
        ('M', 'Man'),
        ('W', 'Woman'),
    ]
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    # between 1 and 5
    pace_of_losing_weight = models.IntegerField(default=3)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'date_of_birth', 'sex', 'height', 'weight', 'pace_of_losing_weight')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'date_of_birth', 'sex',
                  'height', 'weight', 'pace_of_losing_weight',
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .models import User


def registeruser(request):
    if request.method == 'GET':
        return render(request, 'account/register.html')
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['email'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('userpage')
            except IntegrityError:
                return render(request, 'account/register.html', {'error': 'That email has already been used.'})

        else:
            return render(request, 'account/register.html', {'error': 'Passwords must match.'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'account/login.html')
    else:
        user = authenticate(request, email=request.POST['email'], password=request.POST['password'])
        if user is None:
            return render(request, 'account/login.html', {'error': 'Email or Passwords is wrong.'})
        else:
            login(request, user)
            return redirect('userpage')

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .models import User


def registeruser(request):
    if request.method == 'GET':
        return render(request, 'accounts/register.html')
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['email'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('userpage')
            except IntegrityError:
                return render(request, 'accounts/register.html', {'error': 'That email has already been used.'})

        else:
            return render(request, 'accounts/register.html', {'error': 'Passwords must match.'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'accounts/login.html')
    else:
        user = authenticate(request, email=request.POST['email'], password=request.POST['password'])
        if user is None:
            return render(request, 'accounts/login.html', {'error': 'Email or Passwords is wrong.'})
        else:
            login(request, user)
            return redirect('userpage')

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Login {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'account/login.css' %}">
{% endblock %}

{% block content %}

<div class="text-center">
  <form class="form-signin bg-light rounded" method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal text-secondary">Login</h1>
    <input type="email" class="form-control" placeholder="Email address" name="email" required>
    <input type="password" class="form-control" placeholder="Password" name="password" required>
    <button class="btn btn-lg btn-primary btn-block btn-submit" type="submit">Login</button>
  </form>

  <p class="pt-5">Don't you have your account? <a href="{% url 'accounts:register' %}">Register</a></p>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Register {% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'account/login.css' %}">
{% endblock %}

{% block content %}

<div class="text-center">
  <form class="form-signin bg-light rounded" method="POST" action="{% url 'accounts:register' %}">
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal text-secondary">Register</h1>
    <input type="email" class="form-control" placeholder="Email address" name="email" required>
    <input type="password" class="form-control" placeholder="Password" name="password1" required>
    <input type="password" class="form-control" placeholder="Password Confirm" name="password2" required>
    <button class="btn btn-lg btn-primary btn-block btn-submit" type="submit">Register</button>
  </form>

  <p class="pt-5">Do you already have your account? <a href="{% url 'accounts:login' %}">Login</a></p>
</div>

{% endblock %}