accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # Auth
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('register/', views.registeruser, name='register'),
]

diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    # Diet
    path('add/measured/', views.addmeasured, name='addmeasured'),
    path('add/diet', views.adddiet, name='adddiet'),
]

losingweight/urls.py
from django.contrib import admin
from django.urls import path, include
import diet.views, accounts.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', diet.views.home, name='home'),
    # Auth
    path('accounts/', include('accounts.urls')),
    # Diet
    path('diet/', include('diet.urls')),
    # Measured
    path('measured/', include('measured.urls')),
    # User
    path('user/', diet.views.userpage, name='userpage'),
]

measured/urls.py
from django.urls import path
from . import views

app_name = 'measured'

urlpatterns = [
    # Diet
    path('add/', views.add, name='add'),
]

diet/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Diet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    name = models.CharField(max_length=100)
    calorie = models.IntegerField()

    def __str__(self):
        return self.name

diet/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db.models import Sum
from datetime import datetime
from accounts.models import User
from diet.models import Diet
from measured.models import Measured

def home(request):
    return render(request, 'diet/home.html')

@login_required
def userpage(request):
    diets = Diet.objects.filter(user=request.user, date=timezone.now())
    try:
        measured = Measured.objects.get(user=request.user, measured_date=timezone.now())
    except Measured.DoesNotExist:
        measured = None
    calorie__sum = diets.aggregate(Sum('calorie'))['calorie__sum']
    return render(request, 'diet/userpage.html', {'diets': diets, 'calorie__sum': calorie__sum, 'measured': measured})

@login_required
def add(request):
    if request.method == 'GET':
        return render(request, 'diet/add.html')
    else:
        try:
            date = datetime.strptime(request.POST['date'], '%Y-%m-%d')
        except ValueError:
            return render(request, 'diet/add.html', {'error': 'Format of date is not proper.'})
        diet = Diet(name=request.POST['name'], calorie=request.POST['calorie'], date=request.POST['date'], user=request.user)
        diet.save()
        return redirect('userpage')

diet/templates/diet/add.html
{% extends 'base.html' %}

{% block content %}

<main role="main" class="inner cover">
    <h3 class="mb-3 font-weight-normal text-center">Create</h3>
    <form class="form-signin" method="POST" action="{% url 'diet:add' %}">
      {% csrf_token %}
      <div class="mx-auto col-md-6 mt-3 mb-3">
        <input class="form-control" type="text" name="name" placeholder="Food Name" required>
        <input class="form-control" type="number" name="calorie" placeholder="Calorie" min="0" required>
        <input class="form-control mb-3" type="date" name="date" value="{% now 'Y-m-d' %}">
        <button class="btn btn-lg btn-primary btn-block btn-submit" type="submit">Add Diet</button>
      </div>
    </form>
</main>

{% endblock %}

diet/templates/diet/addmeasured.html
{% extends 'base.html' %}

{% block content %}

<main role="main" class="inner cover mx-auto">
  <h1 class="cover-heading">Add Measured</h1>
  <p class="lead">Here is {{user}} page.</p>
  <p class="lead">
    <a href="{% url 'diet:addmeasured' %}" class="btn btn-lg btn-primary">Add data</a>
  </p>
</main>

{% endblock %}

diet/templates/diet/home.html
{% extends 'base.html' %}

{% block content %}

<main role="main" class="inner cover mx-auto text-center">
  <h1 class="cover-heading">Now, You Slim.</h1>
  <p class="lead">It's the time to move on. You all have a power making you slim!</p>
  <p class="lead">
    {% if user.is_authenticated %}
    <a href="{% url 'userpage' %}" class="btn btn-lg btn-primary">Start Work!</a>
    {% else %}
    <a href="{% url 'accounts:register' %}" class="btn btn-lg btn-primary">Register Now</a>
    {% endif %}
  </p>
</main>

{% endblock %}

diet/templates/diet/userpage.html
{% extends 'base.html' %}

{% block content %}

<main role="main" class="inner cover mx-auto text-center">
  {% if calorie__sum is None %}
  <h1 class="cover-heading">No diets today🤔</h1>
  {% else %}
  <h1 class="cover-heading">Today's Diets - {{calorie__sum}}kcal</h1>
  {% endif%}

  <!-- measured -->
  {% if measured is None %}
  <p class="lead">No measured data today. <a href="{% url 'measured:add' %}" class="btn btn-sm btn-primary float-right">Add measured data</a></p>
  {% else %}
  <p class="lead">{{measured.weight}}kg, {{measured.body_fat_per}}%</p>
  {% endif%}
  
  <!-- diet -->
  {% if diets is None %}
  <p class="lead">No measured data today. <a href="{% url 'measured:add' %}" class="btn btn-sm btn-primary float-right">Add measured data</a></p>
  {% else %}
  <div class="list-group mb-3">
    {% for diet in diets %}
    <a class="list-group-item list-group-item-action text-secondary">{{diet}} - {{diet.calorie}}kcal</a>
    {% endfor %}
  </div>
  <a href="{% url 'diet:add' %}" class="btn btn-sm btn-primary">Add diet</a>
  {% endif %}

</main>



{% endblock %}